### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by boehser-enkel** [mercenaruss/zigstar_addons#11]
Hi,

looks very promising. Is it possible that you publish a docker image? I'm running docker and can't use the addon

greetings

**Comment by mercenaruss** [comment]
Hi @alexdelprete @boehser-enkel images are available on github:
docker pull ghcr.io/mercenaruss/aarch64-addon-zigstar-cc2652-flasher:0.3.0

https://github.com/mercenaruss/zigstar_addons/pkgs/container/amd64-addon-zigstar-cc2652-flasher

**Comment by alexdelprete** [comment]
Thanks @mercenaruss. I thought those were specific to HA, that's why I asked.

How would we use that without the HA UI? How do we set options etc., env vars? If you could give an example I would really appreciate it.

**Comment by mercenaruss** [comment]
Ohhh, i didn't think about this.
They are specific to HA Addons,they are build from addon template.
Unfortunately dont have any knowledge what will help you on this.
