### ISSUE TITLE
Sonoff zbdongle-p update failed: unable to start service cc2652-flasher: command exited 7

### ISSUE THREAD

**Issue by hillmar** [mercenaruss/zigstar_addons#12]
I'm trying to update my Sonoff zbdongle-p, which is connected over ethernet trough a RasPi running ser2net, but it failes.

This is my configuration
![image](https://github.com/mercenaruss/zigstar_addons/assets/4633132/7a2e6031-9858-46c9-8cf7-b90833b0c698)

And here is my log

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service banner: starting
> 
> -----------------------------------------------------------
>  Add-on: ZigStar TI CC2652P/P7 FW Flasher
>  ZigStar TI CC2652P/P7 firmware flasher add-on
> -----------------------------------------------------------
>  Add-on version: 0.3.0
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 11.1  (amd64 / qemux86-64)
>  Home Assistant Core: 2023.11.3
>  Home Assistant Supervisor: 2023.11.6
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service banner successfully started
> s6-rc: info: service cc2652-flasher: starting
> [13:34:55] INFO: Triggering Bootloader mode on 10.0.1.33:
> [13:34:55] INFO: cc2652-flasher-up script exited with code 7
> s6-rc: warning: unable to start service cc2652-flasher: command exited 7
> s6-rc: info: service banner: stopping
> s6-rc: info: service banner successfully stopped
> /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
> /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by mercenaruss** [comment]
1. Please activate Sonoff USB toggle
2. Disable bootloader mode toggle

**Comment by mercenaruss** [comment]
Ohh wait,is over network.
I dont think this is possbile,at least i dont know how to do it.

**Comment by hillmar** [comment]
Thank you.
It seems like it is the automatic enabling of boot loader that is not working for my setup. 
I tried enabling the bootloader manually by pressing the button when inserting the stick into the RasPi, and then flashing with Sonoff USB toggle "on" and Bootloader mode toggle "off". That worked flawless!
