### ISSUE TITLE
Zigbee2MQTT not starting after flush

### ISSUE THREAD

**Issue by nicocoetzee** [mercenaruss/zigstar_addons#13]
I am reaching out for some assistance with my SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P. I followed the setup instructions (ZigStar TI CC2652 FW Flasher) similar to your guide and the flasher log indicates everything went smoothly. However, I'm experiencing an issue with Zigbee2MQTT. When I try to start it, I'm getting an error as shown in this link: https://t.ly/Rxw3_. This has resulted in my Zigbee network being currently non-functional. I would really appreciate any guidance or support you could offer to resolve this issue. Thank you in advance for your time and help!

**Comment by nicocoetzee** [comment]
I think I found the problem. I installed the router firmware vs. coordinator. But now I cannot update the correct firmware. I get the below error. Any advice would be greatly appreciated.

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting

-----------------------------------------------------------
 Add-on: ZigStar TI CC2652P/P7 FW Flasher
 ZigStar TI CC2652P/P7 firmware flasher add-on
-----------------------------------------------------------
 Add-on version: 0.3.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.11.3
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service cc2652-flasher: starting
[10:12:20] INFO: Starting CC2652P flasher with Sonoff /dev/ttyUSB2
Setting filename to /root/firmware.hex
sonoff
Opening port /dev/ttyUSB2, baud 500000
Reading data from /root/firmware.hex
Your firmware looks like an Intel Hex file
Connecting to target...
ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'
[10:12:22] INFO: cc2652-flasher-up script exited with code 1
s6-rc: warning: unable to start service cc2652-flasher: command exited 1
s6-rc: info: service banner: stopping
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by mercenaruss** [comment]
Hi, sorry i think you will need to put manually in bootlooader mode.
I'm not sure,because i dont have this device on hands.
