### ISSUE TITLE
Unable to flash Slae.sh CC2652RB stick

### ISSUE THREAD

**Issue by Stooovie** [mercenaruss/zigstar_addons#17]
Slae-sh CC2652RB stick. Presumably Silicon Labs:
![Screenshot 2023-12-31 at 12 54 09](https://github.com/mercenaruss/zigstar_addons/assets/10572373/4f8ce9d0-97ce-42db-aef6-2f1a790f1d96)

so, using ZigStar Silicon Labs FW Flasher:
![Screenshot 2023-12-31 at 12 55 28](https://github.com/mercenaruss/zigstar_addons/assets/10572373/1315f735-8ae6-4500-bf59-cd105c9bd784)

this is the FW URL:

https://raw.githubusercontent.com/Koenkk/Z-Stack-firmware/Z-Stack_3.x.0_coordinator_20230507/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20230507.zip

But getting this:
```
[12:29:55] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (bootloader baudrate 115200)
Error: '/root/firmware.gbl' does not appear to be a valid GBL image: ValidationError('Image is truncated: tag value is cut off')
```

Any ideas? Thanks!

**Comment by mercenaruss** [comment]
Hi, slaesg stick is using Cc2652Ra,use TI addon
