### ISSUE TITLE
[Help] Issue flashing

### ISSUE THREAD

**Issue by giopas** [mercenaruss/zigstar_addons#22]
I'd like to flash my SONOFF Zigbee 3.0 USB Dongle Plus V2 to use it as repeater, instead as controller (I have two of them, so I can cover the whole house) through this addon and I receive the following error (after having disabled ZigBee Home Automation):

```
Failed to save add-on configuration, Missing required option 'network _device' in ZigStar TI
CC2652P/P7 FW Flasher (193f5383_zigstar- cc2652p-flasher). Got {'device': '/dev/serial/by- id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008084230-if00', 'network _device': None, 'usb_mode': False, 'sonoff: True, 'launchpad_fw': True, 'cc1352p7_fw: False, 'other_fw': False, 'firmware_url': ", 'trigger_bsl': False)
```

For info:
HA Core 2024.1.3
HA Supervisor 2023.12.0
Operating System 11.4
Installed on rpi4

Not sure what I am missing. Any help, please?

**Comment by giopas** [comment]
Sorry, could you better explain? The dongle is in the USB socket of the RPI (the same where HA runs). What should I put?

**Comment by mercenaruss** [comment]
You have 2 situations:
1. Flashing USB

then on network:port you write any characters,for example: blabla

2. You flash network device,like UZG-01

Then you choose a dummy USB

**Comment by giopas** [comment]
Thank you, I will try then!!

**Comment by giopas** [comment]
I tried, but I get the following error:

> ERROR: Could not open port socket://aaaa: '<=' not supported between instances of 'int' and 'NoneType'
> [23:57:25] INFO: cc2652-flasher-up script exited with code 1

Here is the complete log, what I am missing?

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service banner: starting
> 
> -----------------------------------------------------------
>  Add-on: ZigStar TI CC2652P/P7 FW Flasher
>  ZigStar TI CC2652P/P7 firmware flasher add-on
> -----------------------------------------------------------
>  Add-on version: 0.4.0
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 11.4  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2024.1.3
>  Home Assistant Supervisor: 2023.12.1
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service banner successfully started
> s6-rc: info: service cc2652-flasher: starting
> [23:57:25] INFO: Starting CC2652P flasher with Sonoff socket://aaaa
> Setting filename to /root/firmware.hex
> ERROR: Could not open port socket://aaaa: '<=' not supported between instances of 'int' and 'NoneType'
> [23:57:25] INFO: cc2652-flasher-up script exited with code 1
> s6-rc: warning: unable to start service cc2652-flasher: command exited 1
> s6-rc: info: service banner: stopping
> /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
> /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
> s6-rc: info: service banner successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by giopas** [comment]
Ok, I made some steps further, thanks to this post[1] and the documentation tab on Addon.

Here is the configuration YAML:

> device: >-
>   /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008085110-if00
> network_device: nn
> usb_mode: true
> sonoff: true
> launchpad_fw: false
> cc1352p7_fw: false
> other_fw: false
> firmware_url: >-
>   https://github.com/Koenkk/Z-Stack-firmware/raw/7398d834eb3a790876c280293c4181da96cc7114/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20221226.zip
> trigger_bsl: false

I have therefore started the add-on and I got this error:

`ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'`

Here is the full log:

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service banner: starting
> 
> -----------------------------------------------------------
>  Add-on: ZigStar TI CC2652P/P7 FW Flasher
>  ZigStar TI CC2652P/P7 firmware flasher add-on
> -----------------------------------------------------------
>  Add-on version: 0.4.0
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 11.4  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2024.1.3
>  Home Assistant Supervisor: 2023.12.1
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service banner successfully started
> s6-rc: info: service cc2652-flasher: starting
> [22:13:47] INFO: Starting CC2652P flasher with Sonoff /dev/ttyACM0
> Setting filename to /root/firmware.hex
> sonoff
> Opening port /dev/ttyACM0, baud 500000
> Reading data from /root/firmware.hex
> Your firmware looks like an Intel Hex file
> Connecting to target...
> ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'
> [22:13:49] INFO: cc2652-flasher-up script exited with code 1
> s6-rc: warning: unable to start service cc2652-flasher: command exited 1
> s6-rc: info: service banner: stopping
> /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
> /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
> s6-rc: info: service banner successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

What am I missing now?

Thanks!

ps: https://forum.hacf.fr/t/flasher-sa-cle-sonoff-zigbee-3-0-modele-p-avec-ladd-on-zigstar/31288

**Comment by mercenaruss** [comment]
Sorry for late response,you missed maybe that you have ZHA or Z2M activated.
Router firmware is used to extend the network.

**Comment by TylonHH** [comment]
and you nees to stop the addon before editing the config, it wont save new settings
