### ISSUE TITLE
[REQUEST] Look at patches from darkxst for his multipan flasher fork of the Silabs Flasher

### ISSUE THREAD

**Issue by Hedda** [mercenaruss/zigstar_addons#23]
FYI, darkxst has a downstream fork of Silabs Flasher add-on with patches that might be interested in looking at for your fork of it:

https://github.com/darkxst/multipan_flasher

https://github.com/darkxst/multipan_flasher/pulls?q=is%3Apr

https://github.com/darkxst/multipan_flasher/blob/main/multipan_flasher/DOCS.md

Thinking that perhaps him and you are also interested in collaborating on some patches from your own Silabs Flasher fork:

https://github.com/mercenaruss/zigstar_addons/tree/main/zigstar-silabs-flasher

https://github.com/mercenaruss/zigstar_addons/blob/main/zigstar-silabs-flasher/DOCS.md

**Comment by mercenaruss** [comment]
Currently no any work in ongoing for Silabs Flasher,will update once i have time for this.
