### ISSUE TITLE
Error on saving configuration for LAN update in HASS.IO.

### ISSUE THREAD

**Issue by robertp007** [mercenaruss/zigstar_addons#26]
Hi,
I am running the current HASS.IO on a Raspberry4.
I connected the Zigbee coordinator UZG-01 via Lan.
Unfortunately, the configuration for the add-on to flash the firmware does not work.
I have not configured a TTY port in the system.
When I specify the IP address with the port and want to save the configuration, the following error occurs:

Error saving add-on configuration, Missing required option 'device' in ZigStar TI CC2652P7 FW Flasher (193f5383_zigstar-cc2652p7-flasher).
Got {'device': None, 'network_device': '192.168.10.153:6638', 'usb_mode': False, 'coordinator_fw': True, 'router_fw': False, 'firmware_url': '', 'trigger_bsl': True }

There is no input field for Device. Furthermore, this information is not relevant for pure LAN access.

What is the problem and how can I solve it?

**Comment by mercenaruss** [comment]
Hello,this will be added to documentation.
You can edit yam file directly and write anything for TTY device,addon will start.
