### ISSUE TITLE
Installation of 20240710 coordinator firmware fails on Sonoff ZigbeeDongle Plus

### ISSUE THREAD

**Issue by ObadahFahmy** [mercenaruss/zigstar_addons#46]
When trying to update a Sonoff Zigbee Dongle plus with the [latest coordinator version](https://github.com/Koenkk/Z-Stack-firmware/raw/85d2fc7a6c10dab0cfb4c4b413740ef7d258a78f/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20240710.zip) from 2024-07-10, the update fails to install due to an error decoding the firmware zip file. 

Relevant log line:
`ERROR: 'utf-8' codec can't decode byte 0xcb in position 7008: invalid continuation byte`

Switching to [the previous version](https://github.com/Koenkk/Z-Stack-firmware/blob/15c27041a562b197f94ca197be0670388ef5c623/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20230507.zip) for 2023-05-07 successfully installs without any errors.

Full logs:
-----------------------------------------------------------
 Add-on: ZigStar TI CC2652P/P7 FW Flasher
 ZigStar TI CC2652P/P7 firmware flasher add-on
-----------------------------------------------------------
 Add-on version: 0.4.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.8.3
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service cc2652-flasher: starting
[20:00:29] INFO: Starting CC2652P flasher with Sonoff /dev/ttyUSB0
Setting filename to /root/firmware.hex
sonoff
Opening port /dev/ttyUSB0, baud 500000
Reading data from /root/firmware.hex
Your firmware looks like an Intel Hex file
ERROR: 'utf-8' codec can't decode byte 0xcb in position 7008: invalid continuation byte
[20:00:29] INFO: cc2652-flasher-up script exited with code 1
s6-rc: warning: unable to start service cc2652-flasher: command exited 1
s6-rc: info: service banner: stopping
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by ObadahFahmy** [comment]
Temporary fix is to install the previous version as mentioned above, but a fix for the new firmware version is needed.

**Comment by VasiliyNovosad** [comment]
Workaround to use straight URL to the firmware https://github.com/mercenaruss/zigstar_addons/issues/44#issuecomment-2312559723

**Comment by ObadahFahmy** [comment]
Thanks! Closing as duplicate of #44
